#include <proc/alloc.h>
#include <proc/devname.h>
#include <proc/escape.h>
#include <proc/procps.h>
#include <proc/pwcache.h>
#include <proc/readproc.h>
#include <proc/sig.h>
#include <proc/slab.h>
#include <proc/sysinfo.h>
#include <proc/version.h>
#include <proc/wchan.h>
#include <proc/whattime.h>
